server:
  port: 8888

spring:
  application:
    name: elema-provider-tdc
  datasource:
     url: jdbc:mysql://localhost:3306/elema_tdc
     username: root
     password: 123456
     driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 172.20.10.10
    port: 6379
mybatis:
  mapper-locations: classpath:/mapper/**

